spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matzzang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dbstmdgur123!@#

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

server:
  port: 8080

jwt:
  secret: S3cR3tT0k3nForJWTShouldBe32Bytes!
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
